version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:80"
    networks:
      - "desafio-network"
    depends_on:
      - api

  api:
      build:
        context: .
        dockerfile: api/Dockerfile
      ports:
        - "5185:5185"
      networks:
        - "desafio-network"
      depends_on:
        - db

  db:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      ports:
        - "1433:1433"
      networks:
        - "desafio-network"
      environment:
          SA_PASSWORD: "S3cur3P@ssW0rd!"
          ACCEPT_EULA: "Y"
networks:
  desafio-network:
    driver: bridge